name: INF 380P Fall 2021

title: INF 380P

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/Chicago

github_repo_url: https://github.com/inf380p/inf380p.github.io
gitter_room: inf380p/fall2021
zoom_url: https://utexas.zoom.us/j/97495200087
canvas_url: https://utexas.instructure.com/courses/1313369

plugins:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Don't serve these files/dirs.
exclude: [vendor, script]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - materials
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

# If this gets archived at a different URL make sure to delete the blank statements at the bottom
baseurl: /fall2021
url: /fall2021

python: true

course:
  title: Introduction to Programming
  number: INF 380P
  instructor: Prof. Elliott Hauser
  ta: Misha Coleman
  semester: Fall 2021
  location: "UTA 1.208"

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: https://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  "Elliott Hauser is an Assistant Professor at the UT Austin iSchool.  He's hacking education as one of the cofounders of Trinket.io."

  MishaCienfuegos:
    name: Misha Coleman
    prof: true
    gravatar:
    website:
    github: MishaCienfuegos
    twitter: mishacienfuegos
    about: "Misha is the course's Teaching Assistant, currently in her second year of the MSIS program at the iSchool. Previously, she worked as a software developer, learning to code on the job. She loves exploring the world by bike! :bike:"

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Turtle"
    github: tommytester
    twitter:
    about: "Testin' course websites since 2014."

  acreese:
    name: acreese
    prof: false
    gravatar:
    website: "#"
    github: acreese
    twitter:
    about: "Here's a little about acreese"

  agunnells:
    name: agunnells
    prof: false
    gravatar:
    website: "#"
    github: agunnells
    twitter:
    about: "Here's a little about agunnells"

  alueker:
    name: alueker
    prof: false
    gravatar:
    website: "#"
    github: alueker
    twitter:
    about: "Here's a little about alueker"

  amanda-guerrero:
    name: amanda-guerrero
    prof: false
    gravatar:
    website: "#"
    github: amanda-guerrero
    twitter:
    about: "Here's a little about amanda-guerrero"

  apurva-shah515:
    name: apurva-shah515
    prof: false
    gravatar:
    website: https://apurvashah1897.myportfolio.com/
    github: apurva-shah515
    twitter:
    about: "2nd Year in the MSIS program, looking to learn more about Python. Also interested in other languages like React and JavaScript!"

  areiter18:
    name: areiter18
    prof: false
    gravatar:
    website: "#"
    github: areiter18
    twitter:
    about: "Here's a little about areiter18"

  ArisWells:
    name: ArisWells
    prof: false
    gravatar:
    website: "#"
    github: ArisWells
    twitter:
    about: "Here's a little about ArisWells"

  AU-turtledragon:
    name: AU-turtledragon
    prof: false
    gravatar:
    website: "#"
    github: AU-turtledragon
    twitter:
    about: "Here's a little about AU-turtledragon"

  benderliz:
    name: benderliz
    prof: false
    gravatar:
    website: "#"
    github: benderliz
    twitter:
    about: "Here's a little about benderliz"

  boyeonpark:
    name: boyeonpark
    prof: false
    gravatar:
    website: "#"
    github: boyeonpark
    twitter:
    about: "Here's a little about boyeonpark"

  choim7:
    name: choim7
    prof: false
    gravatar:
    website: "#"
    github: choim7
    twitter:
    about: "Here's a little about choim7"

  cmr4658:
    name: cmr4658
    prof: false
    gravatar:
    website: "#"
    github: cmr4658
    twitter:
    about: "Here's a little about cmr4658"

  cridley17:
    name: cridley17
    prof: false
    gravatar:
    website: "#"
    github: cridley17
    twitter:
    about: "Here's a little about cridley17"

  Elizard0926:
    name: Elizard0926
    prof: false
    gravatar:
    website: "#"
    github: Elizard0926
    twitter:
    about: "Here's a little about Elizard0926"

  hdubbe:
    name: hdubbe
    prof: false
    gravatar:
    website: "#"
    github: hdubbe
    twitter:
    about: "Here's a little about hdubbe"

  IMBLAH:
    name: IMBLAH
    prof: false
    gravatar:
    website: "#"
    github: IMBLAH
    twitter:
    about: "Here's a little about IMBLAH"

  itohosagie:
    name: itohosagie
    prof: false
    gravatar:
    website: "#"
    github: itohosagie
    twitter:
    about: "Here's a little about itohosagie"

  lulomax:
    name: lulomax
    prof: false
    gravatar:
    website: "#"
    github: lulomax
    twitter:
    about: "Here's a little about lulomax"

  sarahva47:
    name: sarahva47
    prof: false
    gravatar:
    website: "#"
    github: sarahva47
    twitter:
    about: "Here's a little about sarahva47"

  scyrill:
    name: scyrill
    prof: false
    gravatar:
    website: "#"
    github: scyrill
    twitter:
    about: "Here's a little about scyrill"

  sj-roh:
    name: sj-roh
    prof: false
    gravatar:
    website: "#"
    github: sj-roh
    twitter:
    about: "Here's a little about sj-roh"

  spinachleaf:
    name: spinachleaf
    prof: false
    gravatar:
    website: "#"
    github: spinachleaf
    twitter:
    about: "Here's a little about spinachleaf"

  srj1220:
    name: srj1220
    prof: false
    gravatar:
    website: "#"
    github: srj1220
    twitter:
    about: "Here's a little about srj1220"

  vannyyeh:
    name: vannyyeh
    prof: false
    gravatar:
    website: "#"
    github: vannyyeh
    twitter:
    about: "Here's a little about vannyyeh"

  weifeng0102:
    name: weifeng0102
    prof: false
    gravatar:
    website: "#"
    github: weifeng0102
    twitter:
    about: "Here's a little about weifeng0102"

  YitongFeng726:
    name: YitongFeng726
    prof: false
    gravatar:
    website: "#"
    github: YitongFeng726
    twitter:
    about: "Here's a little about YitongFeng726"

  zheinsohn:
    name: zheinsohn
    prof: false
    gravatar:
    website: "#"
    github: zheinsohn
    twitter:
    about: "Here's a little about zheinsohn"


baseurl:
url:
