name: INF 380P Fall 2020

title: INF 380P

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/New_York

github_repo_url: https://github.com/inf380p/inf380p.github.io
gitter_room: inf380p/fall2020

plugins:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - materials
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

# If this gets archived at a different URL make sure to delete the blank statements at the bottom
baseurl: /fall2020
url: /fall2020

python: true

course:
  title: Introduction to Programming
  number: INF 380P
  instructor: Prof. Elliott Hauser
  semester: Fall 2020

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: http://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  Elliott Hauser is an Assistant Professor at the UT Austin iSchool.  He's hacking education as one of the cofounders of Trinket.io.

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Turtle"
    github: tommytester
    twitter:
    about: "Testin' course websites since 2014."

  akef:
    name: Akef Ebeid
    prof: false
    gravatar:
    website: "https://en.wikipedia.org/wiki/Turtle"
    github: iebeid
    twitter:
    about: TA extraordinaire.

  a-larasati:
    name: a-larasati
    prof: false
    gravatar:
    website: "#"
    github: a-larasati
    twitter:
    about: "Here's a little about a-larasati"

  bmb4227:
    name: bmb4227
    prof: false
    gravatar:
    website: "#"
    github: bmb4227
    twitter:
    about: "Here's a little about bmb4227"

  brianna-stedman:
    name: brianna-stedman
    prof: false
    gravatar:
    website: "#"
    github: brianna-stedman
    twitter:
    about: "Here's a little about brianna-stedman"

  intjnotinfp:
    name: intjnotinfp
    prof: false
    gravatar:
    website: "#"
    github: intjnotinfp
    twitter:
    about: "Here's a little about intjnotinfp"

  jasfromnz:
    name: jasfromnz
    prof: false
    gravatar:
    website: "#"
    github: jasfromnz
    twitter:
    about: "Here's a little about jasfromnz"

  KJEZ35:
    name: KJEZ35
    prof: false
    gravatar:
    website: "#"
    github: KJEZ35
    twitter:
    about: "Here's a little about KJEZ35"

  luznette:
    name: luznette
    prof: false
    gravatar:
    website: "#"
    github: luznette
    twitter:
    about: "Here's a little about luznette"

  pccisme:
    name: pccisme
    prof: false
    gravatar:
    website: "#"
    github: pccisme
    twitter:
    about: "Here's a little about pccisme"

